# CMake generated Testfile for 
# Source directory: /Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc
# Build directory: /Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/morton_test[1]_include.cmake")
include("/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/hilbert_test[1]_include.cmake")
add_test([=[MortonCodeTest.EncodeDecode2D]=] "/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/morton_test" "--gtest_filter=MortonCodeTest.EncodeDecode2D")
set_tests_properties([=[MortonCodeTest.EncodeDecode2D]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/gandanie/scratch/santis/mars/cmake/Tests.cmake;41;gtest_add_tests;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;3;mars_add_test;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;0;")
add_test([=[MortonCodeTest.EncodeDecode3D]=] "/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/morton_test" "--gtest_filter=MortonCodeTest.EncodeDecode3D")
set_tests_properties([=[MortonCodeTest.EncodeDecode3D]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/gandanie/scratch/santis/mars/cmake/Tests.cmake;41;gtest_add_tests;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;3;mars_add_test;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;0;")
add_test([=[MortonCodeTest.DecodeMorton3D]=] "/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/morton_test" "--gtest_filter=MortonCodeTest.DecodeMorton3D")
set_tests_properties([=[MortonCodeTest.DecodeMorton3D]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/gandanie/scratch/santis/mars/cmake/Tests.cmake;41;gtest_add_tests;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;3;mars_add_test;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;0;")
add_test([=[MortonCodeTest.decodeMorton64]=] "/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/morton_test" "--gtest_filter=MortonCodeTest.decodeMorton64")
set_tests_properties([=[MortonCodeTest.decodeMorton64]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/gandanie/scratch/santis/mars/cmake/Tests.cmake;41;gtest_add_tests;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;3;mars_add_test;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;0;")
add_test([=[HilbertCode.inversion2D]=] "/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/hilbert_test" "--gtest_filter=HilbertCode.inversion2D")
set_tests_properties([=[HilbertCode.inversion2D]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/gandanie/scratch/santis/mars/cmake/Tests.cmake;41;gtest_add_tests;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;4;mars_add_test;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;0;")
add_test([=[HilbertCode.Hilbert2D]=] "/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/hilbert_test" "--gtest_filter=HilbertCode.Hilbert2D")
set_tests_properties([=[HilbertCode.Hilbert2D]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/gandanie/scratch/santis/mars/cmake/Tests.cmake;41;gtest_add_tests;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;4;mars_add_test;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;0;")
add_test([=[HilbertCode.firstOrderCurve]=] "/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/hilbert_test" "--gtest_filter=HilbertCode.firstOrderCurve")
set_tests_properties([=[HilbertCode.firstOrderCurve]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/gandanie/scratch/santis/mars/cmake/Tests.cmake;41;gtest_add_tests;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;4;mars_add_test;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;0;")
add_test([=[HilbertCode.continuity]=] "/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/hilbert_test" "--gtest_filter=HilbertCode.continuity")
set_tests_properties([=[HilbertCode.continuity]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/gandanie/scratch/santis/mars/cmake/Tests.cmake;41;gtest_add_tests;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;4;mars_add_test;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;0;")
add_test([=[HilbertCode.inversion]=] "/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/hilbert_test" "--gtest_filter=HilbertCode.inversion")
set_tests_properties([=[HilbertCode.inversion]=] PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.28.3/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/gandanie/scratch/santis/mars/cmake/Tests.cmake;41;gtest_add_tests;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;4;mars_add_test;/Users/gandanie/scratch/santis/mars/backend/distributed/testsuite/sfc/CMakeLists.txt;0;")
