if(EXISTS "/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/hilbert_test[1]_tests.cmake")
  include("/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/hilbert_test[1]_tests.cmake")
else()
  add_test(hilbert_test_NOT_BUILT hilbert_test_NOT_BUILT)
endif()
