if(EXISTS "/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/morton_test[1]_tests.cmake")
  include("/Users/gandanie/scratch/santis/mars/mac/backend/distributed/testsuite/sfc/morton_test[1]_tests.cmake")
else()
  add_test(morton_test_NOT_BUILT morton_test_NOT_BUILT)
endif()
