# Distributed SIMPLE gate targets; included by CMakeLists.txt (standalone) or, deferred, by
# ../distributed_matrix/inject.cmake inside a MARS configure. Paths are absolute on purpose.
get_filename_component(_dsimple_root "${CMAKE_CURRENT_LIST_DIR}/../../../.." ABSOLUTE)
set(_dsimple_gates "${CMAKE_CURRENT_LIST_DIR}")
set(_dsimple_segregated "${_dsimple_root}/backend/distributed/unstructured/fem/segregated")
if(NOT TARGET MPI::MPI_CXX)
    find_package(MPI REQUIRED COMPONENTS CXX)
endif()

add_executable(mars_distributed_simple_host_gate "${_dsimple_gates}/simple_gate.cpp")
target_include_directories(mars_distributed_simple_host_gate PRIVATE "${_dsimple_segregated}" "${_dsimple_gates}")
target_compile_features(mars_distributed_simple_host_gate PRIVATE cxx_std_20)
target_compile_definitions(mars_distributed_simple_host_gate PRIVATE OMPI_SKIP_MPICXX=1 MPICH_SKIP_MPICXX=1)
target_link_libraries(mars_distributed_simple_host_gate PRIVATE MPI::MPI_CXX)
add_executable(mars_distributed_halo_host_gate "${_dsimple_gates}/halo_gate.cpp")
target_include_directories(mars_distributed_halo_host_gate PRIVATE "${_dsimple_segregated}")
target_compile_features(mars_distributed_halo_host_gate PRIVATE cxx_std_20)
target_compile_definitions(mars_distributed_halo_host_gate PRIVATE OMPI_SKIP_MPICXX=1 MPICH_SKIP_MPICXX=1)
target_link_libraries(mars_distributed_halo_host_gate PRIVATE MPI::MPI_CXX)
add_executable(mars_simple_domain_view_host_test "${_dsimple_gates}/domain_view_host_test.cpp")
target_include_directories(mars_simple_domain_view_host_test PRIVATE "${_dsimple_segregated}")
target_compile_features(mars_simple_domain_view_host_test PRIVATE cxx_std_20)
target_compile_definitions(mars_simple_domain_view_host_test PRIVATE OMPI_SKIP_MPICXX=1 MPICH_SKIP_MPICXX=1)
target_link_libraries(mars_simple_domain_view_host_test PRIVATE MPI::MPI_CXX)
add_test(NAME marsSimpleDomainView COMMAND mars_simple_domain_view_host_test)
add_executable(mars_simple_mesh_host_gate "${_dsimple_gates}/mesh_gate.cpp")
target_include_directories(mars_simple_mesh_host_gate PRIVATE "${_dsimple_segregated}" "${_dsimple_gates}")
target_compile_features(mars_simple_mesh_host_gate PRIVATE cxx_std_20)
target_compile_definitions(mars_simple_mesh_host_gate PRIVATE OMPI_SKIP_MPICXX=1 MPICH_SKIP_MPICXX=1)
target_link_libraries(mars_simple_mesh_host_gate PRIVATE MPI::MPI_CXX)
# Native file decoding and device-side topology validation use the same fixture gate.
find_path(MARS_SIMPLE_NETCDF_INCLUDE_DIR netcdf.h HINTS ${NETCDF_INCLUDE_DIRS})
find_library(MARS_SIMPLE_NETCDF_LIBRARY netcdf HINTS ${NETCDF_LIBRARY_DIRS})
if(MARS_SIMPLE_NETCDF_INCLUDE_DIR AND MARS_SIMPLE_NETCDF_LIBRARY)
    add_executable(mars_simple_exodus_host_gate "${_dsimple_gates}/exodus_gate.cpp")
    target_include_directories(mars_simple_exodus_host_gate PRIVATE "${_dsimple_segregated}" "${MARS_SIMPLE_NETCDF_INCLUDE_DIR}")
    target_compile_features(mars_simple_exodus_host_gate PRIVATE cxx_std_20)
    target_compile_definitions(mars_simple_exodus_host_gate PRIVATE MARS_HAVE_NETCDF OMPI_SKIP_MPICXX=1 MPICH_SKIP_MPICXX=1)
    target_link_libraries(mars_simple_exodus_host_gate PRIVATE MPI::MPI_CXX "${MARS_SIMPLE_NETCDF_LIBRARY}")
    foreach(_ranks 1 2)
        add_test(NAME marsSimpleExodus${_ranks} COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} ${_ranks} ${MPIEXEC_PREFLAGS}
            $<TARGET_FILE:mars_simple_exodus_host_gate> ${MPIEXEC_POSTFLAGS} "${CMAKE_CURRENT_BINARY_DIR}/exodus-fixtures-${_ranks}" "${_dsimple_root}/tests/data/public_outlet_channel/outlet_channel.exo")
        set_tests_properties(marsSimpleExodus${_ranks} PROPERTIES TIMEOUT 60)
    endforeach()
endif()
foreach(_ranks 1 2 4)
    add_test(NAME marsSimpleMesh${_ranks} COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} ${_ranks} ${MPIEXEC_PREFLAGS}
        $<TARGET_FILE:mars_simple_mesh_host_gate> ${MPIEXEC_POSTFLAGS})
    set_tests_properties(marsSimpleMesh${_ranks} PROPERTIES TIMEOUT 60)
endforeach()
foreach(_fault star identity tag)
    add_test(NAME marsSimpleMeshReject_${_fault} COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} 4 ${MPIEXEC_PREFLAGS}
        $<TARGET_FILE:mars_simple_mesh_host_gate> ${MPIEXEC_POSTFLAGS} ${_fault})
    set_tests_properties(marsSimpleMeshReject_${_fault} PROPERTIES TIMEOUT 60)
endforeach()
foreach(_ranks 1 2 4)
    add_test(NAME marsDistributedHalo${_ranks} COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} ${_ranks} ${MPIEXEC_PREFLAGS}
             $<TARGET_FILE:mars_distributed_halo_host_gate> ${MPIEXEC_POSTFLAGS})
    set_tests_properties(marsDistributedHalo${_ranks} PROPERTIES TIMEOUT 30)
endforeach()
foreach(_fault asymmetric counts offsets duplicate-peer duplicate-recv identity node-overflow)
    add_test(NAME marsDistributedHalo_${_fault} COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} 2 ${MPIEXEC_PREFLAGS}
             $<TARGET_FILE:mars_distributed_halo_host_gate> ${MPIEXEC_POSTFLAGS} ${_fault})
    set_tests_properties(marsDistributedHalo_${_fault} PROPERTIES TIMEOUT 30)
endforeach()
find_package(Python3 QUIET COMPONENTS Interpreter)
if(Python3_Interpreter_FOUND)
    add_test(NAME marsDistributedFieldsComparator COMMAND ${Python3_EXECUTABLE} "${_dsimple_gates}/test_compare_fields.py")
    foreach(_fault stride reverse-stride)
        add_test(NAME marsDistributedHalo_abort_${_fault} COMMAND ${Python3_EXECUTABLE} "${_dsimple_gates}/check_abort.py"
                 ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} 2 ${MPIEXEC_PREFLAGS}
                 $<TARGET_FILE:mars_distributed_halo_host_gate> ${MPIEXEC_POSTFLAGS} ${_fault})
        set_tests_properties(marsDistributedHalo_abort_${_fault} PROPERTIES TIMEOUT 30)
    endforeach()
endif()

# One-rank SimpleRunner references, then distributed comparisons (a stranded rank hangs -> timeout).
function(_dsimple_test name ranks)
    add_test(NAME ${name} COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} ${ranks} ${MPIEXEC_PREFLAGS}
             $<TARGET_FILE:mars_distributed_simple_host_gate> ${MPIEXEC_POSTFLAGS} ${ARGN})
    set_tests_properties(${name} PROPERTIES TIMEOUT 900 PROCESSORS ${ranks})
endfunction()
set(_ref "${CMAKE_CURRENT_BINARY_DIR}/dsimple")
_dsimple_test(marsDistributedSimpleReference 1 --write-reference ${_ref}-2it.bin)
_dsimple_test(marsDistributedSimpleReferenceShear 1 --write-reference ${_ref}-shear.bin --backflow -1 --iterations 12)
_dsimple_test(marsDistributedSimpleReferenceClosed 1 --write-reference ${_ref}-closed.bin --backflow 1 --iterations 8)
_dsimple_test(marsDistributedSimpleReferenceConverge 1 --write-reference ${_ref}-conv.bin --mesh 8x2x2 --converge 4000)
set_tests_properties(marsDistributedSimpleReference marsDistributedSimpleReferenceShear marsDistributedSimpleReferenceClosed
    marsDistributedSimpleReferenceConverge PROPERTIES FIXTURES_SETUP dsimple_references)
set(_compare)
foreach(_ranks 1 2 4)
    _dsimple_test(marsDistributedSimple2it_${_ranks} ${_ranks} --reference ${_ref}-2it.bin)
    _dsimple_test(marsDistributedSimpleShear_${_ranks} ${_ranks} --reference ${_ref}-shear.bin --backflow -1 --iterations 12)
    _dsimple_test(marsDistributedSimpleClosed_${_ranks} ${_ranks} --reference ${_ref}-closed.bin --backflow 1 --iterations 8)
    _dsimple_test(marsDistributedSimpleConverge_${_ranks} ${_ranks} --reference ${_ref}-conv.bin --mesh 8x2x2 --converge 4000)
    list(APPEND _compare marsDistributedSimple2it_${_ranks} marsDistributedSimpleShear_${_ranks}
                         marsDistributedSimpleClosed_${_ranks} marsDistributedSimpleConverge_${_ranks})
endforeach()
foreach(_ranks 2 4)
    foreach(_fault stale-ghost missing-element duplicate-face)
        _dsimple_test(marsDistributedSimpleFault_${_fault}_${_ranks} ${_ranks} --reference ${_ref}-2it.bin --fault ${_fault})
        list(APPEND _compare marsDistributedSimpleFault_${_fault}_${_ranks})
    endforeach()
endforeach()
# The same comparisons through the production builder (simple_partition on ElementDomain-shaped
# state), and its collective rejection of an incomplete element star.
foreach(_ranks 1 2 4)
    _dsimple_test(marsDistributedSimpleBuilder2it_${_ranks} ${_ranks} --reference ${_ref}-2it.bin --builder 1)
    _dsimple_test(marsDistributedSimpleBuilderShear_${_ranks} ${_ranks} --reference ${_ref}-shear.bin --backflow -1 --iterations 12 --builder 1)
    list(APPEND _compare marsDistributedSimpleBuilder2it_${_ranks} marsDistributedSimpleBuilderShear_${_ranks})
endforeach()
foreach(_ranks 2 4)
    _dsimple_test(marsDistributedSimpleBuilderIncompleteStar_${_ranks} ${_ranks} --reference ${_ref}-2it.bin --builder 1 --fault missing-element)
    list(APPEND _compare marsDistributedSimpleBuilderIncompleteStar_${_ranks})
endforeach()
set_tests_properties(${_compare} PROPERTIES FIXTURES_REQUIRED dsimple_references)
_dsimple_test(marsDistributedSimpleSubcommunicators 4 --reference ${_ref}-2it.bin --builder 1 --split 1)
set_tests_properties(marsDistributedSimpleSubcommunicators PROPERTIES FIXTURES_REQUIRED dsimple_references TIMEOUT 120)

if(TARGET mars AND MARS_ENABLE_CUDA AND MARS_ENABLE_HYPRE)
    add_executable(mars_distributed_halo_cuda_gate "${_dsimple_gates}/halo_gate.cu")
    target_link_libraries(mars_distributed_halo_cuda_gate PRIVATE mars)
    target_include_directories(mars_distributed_halo_cuda_gate PRIVATE "${_dsimple_segregated}")
    set_target_properties(mars_distributed_halo_cuda_gate PROPERTIES CUDA_STANDARD 20 CUDA_STANDARD_REQUIRED ON)
    # Mirrors mars_segregated_simple: link mars, MARS_REPLAY_CUDA, CUDA C++20.
    add_executable(mars_distributed_simple_cuda_gate "${_dsimple_gates}/simple_gate.cu")
    target_link_libraries(mars_distributed_simple_cuda_gate PRIVATE mars)
    target_compile_definitions(mars_distributed_simple_cuda_gate PRIVATE MARS_REPLAY_CUDA)
    target_include_directories(mars_distributed_simple_cuda_gate PRIVATE "${_dsimple_segregated}" "${_dsimple_gates}")
    set_target_properties(mars_distributed_simple_cuda_gate PROPERTIES CUDA_STANDARD 20 CUDA_STANDARD_REQUIRED ON)
    add_executable(mars_simple_mesh_cuda_gate "${_dsimple_gates}/mesh_gate.cu")
    target_link_libraries(mars_simple_mesh_cuda_gate PRIVATE mars)
    target_compile_definitions(mars_simple_mesh_cuda_gate PRIVATE MARS_REPLAY_CUDA)
    target_include_directories(mars_simple_mesh_cuda_gate PRIVATE "${_dsimple_segregated}" "${_dsimple_gates}")
    set_target_properties(mars_simple_mesh_cuda_gate PROPERTIES CUDA_STANDARD 20 CUDA_STANDARD_REQUIRED ON)
    get_target_property(_simple_mars_definitions mars_unstructured INTERFACE_COMPILE_DEFINITIONS)
    if("MARS_HAVE_NETCDF" IN_LIST _simple_mars_definitions)
        add_executable(mars_simple_exodus_cuda_gate "${_dsimple_gates}/exodus_gate.cu")
        target_link_libraries(mars_simple_exodus_cuda_gate PRIVATE mars)
        target_compile_definitions(mars_simple_exodus_cuda_gate PRIVATE MARS_REPLAY_CUDA)
        target_include_directories(mars_simple_exodus_cuda_gate PRIVATE "${_dsimple_segregated}")
        set_target_properties(mars_simple_exodus_cuda_gate PROPERTIES CUDA_STANDARD 20 CUDA_STANDARD_REQUIRED ON)
    endif()
    # Multi-rank public-channel driver on ElementDomain/cstone (same CSV output as mars_segregated_simple).
    add_executable(mars_segregated_simple_mpi "${_dsimple_gates}/simple_mpi_driver.cu")
    target_link_libraries(mars_segregated_simple_mpi PRIVATE mars)
    target_compile_definitions(mars_segregated_simple_mpi PRIVATE MARS_REPLAY_CUDA)
    target_include_directories(mars_segregated_simple_mpi PRIVATE "${_dsimple_segregated}" "${_dsimple_gates}")
    set_target_properties(mars_segregated_simple_mpi PROPERTIES CUDA_STANDARD 20 CUDA_STANDARD_REQUIRED ON)
endif()
