get_filename_component(_simple_perf_root "${CMAKE_CURRENT_LIST_DIR}/../../../.." ABSOLUTE)
set(_simple_perf "${CMAKE_CURRENT_LIST_DIR}")
set(_simple_perf_headers "${_simple_perf_root}/backend/distributed/unstructured/fem/segregated")
add_executable(mars_simple_output_profile_host_gate "${_simple_perf}/output_profile_gate.cpp")
target_include_directories(mars_simple_output_profile_host_gate PRIVATE "${_simple_perf_headers}")
target_compile_features(mars_simple_output_profile_host_gate PRIVATE cxx_std_20)
target_compile_definitions(mars_simple_output_profile_host_gate PRIVATE OMPI_SKIP_MPICXX=1 MPICH_SKIP_MPICXX=1)
target_link_libraries(mars_simple_output_profile_host_gate PRIVATE MPI::MPI_CXX)
if(MARS_SIMPLE_NETCDF_INCLUDE_DIR AND MARS_SIMPLE_NETCDF_LIBRARY)
    add_executable(mars_simple_native_source_host_gate "${_simple_perf}/native_mesh_gate.cpp")
    target_include_directories(mars_simple_native_source_host_gate PRIVATE "${_simple_perf_headers}" "${MARS_SIMPLE_NETCDF_INCLUDE_DIR}")
    target_compile_features(mars_simple_native_source_host_gate PRIVATE cxx_std_20)
    target_compile_definitions(mars_simple_native_source_host_gate PRIVATE MARS_HAVE_NETCDF OMPI_SKIP_MPICXX=1 MPICH_SKIP_MPICXX=1)
    target_link_libraries(mars_simple_native_source_host_gate PRIVATE MPI::MPI_CXX "${MARS_SIMPLE_NETCDF_LIBRARY}")
endif()
foreach(_np 1 2 4)
    set(_output "${CMAKE_CURRENT_BINARY_DIR}/simple-output-${_np}")
    add_test(NAME marsSimpleOutputProfile${_np} COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} ${_np} ${MPIEXEC_PREFLAGS}
        $<TARGET_FILE:mars_simple_output_profile_host_gate> ${MPIEXEC_POSTFLAGS} "${_output}")
    set_tests_properties(marsSimpleOutputProfile${_np} PROPERTIES TIMEOUT 60 FIXTURES_SETUP simple_output_${_np})
    if(Python3_Interpreter_FOUND)
        add_test(NAME marsSimpleOutputCompare${_np} COMMAND ${Python3_EXECUTABLE} "${_simple_perf}/../distributed_simple/compare_fields.py"
            "${_output}/field-fields.csv" "${_output}/field-fields.json")
        set_tests_properties(marsSimpleOutputCompare${_np} PROPERTIES FIXTURES_REQUIRED simple_output_${_np})
    endif()
    if(TARGET mars_simple_native_source_host_gate)
        add_test(NAME marsSimpleNativeSource${_np} COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} ${_np} ${MPIEXEC_PREFLAGS}
            $<TARGET_FILE:mars_simple_native_source_host_gate> ${MPIEXEC_POSTFLAGS}
            "${_simple_perf_root}/tests/data/public_outlet_channel/outlet_channel.exo")
        set_tests_properties(marsSimpleNativeSource${_np} PROPERTIES TIMEOUT 120)
    endif()
endforeach()
if(TARGET mars AND MARS_ENABLE_CUDA AND MARS_ENABLE_HYPRE)
    add_executable(mars_simple_output_profile_cuda_gate "${_simple_perf}/output_profile_gate.cu")
    target_include_directories(mars_simple_output_profile_cuda_gate PRIVATE "${_simple_perf_headers}")
    target_compile_definitions(mars_simple_output_profile_cuda_gate PRIVATE MARS_REPLAY_CUDA)
    target_link_libraries(mars_simple_output_profile_cuda_gate PRIVATE mars)
    set_target_properties(mars_simple_output_profile_cuda_gate PROPERTIES CUDA_STANDARD 20 CUDA_STANDARD_REQUIRED ON)
endif()

_dsimple_test(marsSimpleWaterReference 1 --write-reference "${CMAKE_CURRENT_BINARY_DIR}/simple-water.bin"
    --water 1 --high-resolution 1 --backflow -1 --iterations 4 --mesh 8x2x2)
set_tests_properties(marsSimpleWaterReference PROPERTIES FIXTURES_SETUP simple_water)
foreach(_np 1 2 4)
    _dsimple_test(marsSimpleWater${_np} ${_np} --reference "${CMAKE_CURRENT_BINARY_DIR}/simple-water.bin"
        --water 1 --high-resolution 1 --backflow -1 --iterations 4 --mesh 8x2x2 --builder 1)
    set_tests_properties(marsSimpleWater${_np} PROPERTIES FIXTURES_REQUIRED simple_water)
endforeach()
