pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                echo 'Checking out the repo'
                git branch: 'jenkins', url: 'https://bitbucket.org/zulianp/mars.git'
                sh 'git submodule update --init --recursive'
            }
        }
        stage('build') {
            steps {
                echo 'Building Mars'
                sh 'set -e'
                sh 'set -x'
                sh 'pwd -P'
                sh 'ls -lh'
                sh 'hostname'
                dir('ci/jenkins/cscs/source') {
                    sh 'bash jenkins_submit.sh compute_node_mars.sh'
                }
            }
        }
    }
}
