"""Shared backend bits: launch-default table and flux name maps."""

from ..ir import ElementApply  # noqa: F401  (kept for callers/type context)

# Per-P (BlockSize, ElemsPerBlock) occupancy plan, copied verbatim from
# HoCvfemLaunchDefault in mars_cvfem_ho_matfree.hpp. threadsPerElem = Block/E is
# the smallest warp multiple >= (p+1)^2. Kept in one place so the generated
# launcher and any sweep agree with the hand kernel's validated defaults.
LAUNCH_DEFAULT = {
    1: (256, 64),
    2: (252, 28),
    3: (256, 16),
    4: (256, 8),
    5: (128, 2),
    6: (128, 2),
    7: (128, 2),
    8: (96, 1),
}

# Rendering of the quadrature-slot inputs into each target's variables.
NAMES_CUDA = {
    "deriv": "deriv_cache[it]",
    "dt1": "dt1",
    "dt2": "dt2",
    "g0": "g0",
    "g1": "g1",
    "g2": "g2",
}

NAMES_HOST = {
    "deriv": "deriv[s * n + r]",
    "dt1": "dt1",
    "dt2": "dt2",
    "g0": "g[0]",
    "g1": "g[1]",
    "g2": "g[2]",
}

# Host names for the Jacobian-action (JVP) kernel: the primal quantities plus the
# perturbation (_dot) contractions of the direction du.
NAMES_HOST_JVP = {
    **NAMES_HOST,
    "deriv_dot": "deriv_dot[s * n + r]",
    "dt1_dot": "dt1_dot",
    "dt2_dot": "dt2_dot",
}

# CUDA names for the JVP kernel: primal deriv in a register cache, perturbation
# deriv_dot in its own cache; tangential (dot) derivatives are per-slot scalars.
NAMES_CUDA_JVP = {
    **NAMES_CUDA,
    "deriv_dot": "deriv_dot_cache[it]",
    "dt1_dot": "dt1_dot",
    "dt2_dot": "dt2_dot",
}


def render_flux(ea, names):
    return ea.op.flux.render(names)


AUTOGEN_BANNER = (
    "// AUTO-GENERATED by marsir-compiler from an operator spec. DO NOT EDIT.\n"
    "// Regenerate with: python3 marsir-emit.py <spec>.op --backend {backend}\n"
    "// Source operator: {name}   flux: {flux}\n"
)
