option(MARS_ENABLE_VTK "Uses VTK IO" OFF)
option(MARS_ENABLE_ADIOS2 "Uses ADIOS2 IO" OFF)
option(MARS_USE_CUDA "Build mars with CUDA support" OFF)
option(MARS_NO_RDMA "Build mars with NO RDMA support" OFF)
option(MARS_USE_CUDAUVM "Use as default memory space CUDAUVM. This has only an effect if MARS_USE_CUDA is used too." OFF)
option(MARS_USE_HIP "Build mars with HIP support" OFF)
