option(MARS_ENABLE_MPI "Build mars with MPI support" ON)

option(MARS_ENABLE_KOKKOS "Use -DMARS_ENABLE_KOKKOS=ON for enabling mesh transfer functions." OFF)
option(MARS_ENABLE_KOKKOS_KERNELS "Use -DMARS_ENABLE_KOKKOS_KERNELS=ON for enabling kokkos_kernels" OFF)
option(MARS_ENABLE_CUDA "Build mars with cuda support" OFF)
option(MARS_ENABLE_CUDAUVM "Use as default memory space CUDAUVM. This has only an effect if MARS_ENABLE_CUDA is used too." OFF)
option(MARS_ENABLE_RDMA "Build mars with RDMA support" ON)

option(MARS_ENABLE_HIP "Build mars with cuda support" OFF)

option(MARS_ENABLE_ADIOS2 "Uses ADIOS2 IO" OFF)

# maintainace
option(MARS_ENABLE_BENCHMARK "Enable benchmarks" OFF)
option(MARS_ENABLE_TESTS "Enable tests" ON)

# FIXME Extra backends 
option(MARS_ENABLE_MOONOLITH "Use -DMARS_ENABLE_MOONOLITH=ON for enabling mesh transfer functions." OFF)
option(MARS_ENABLE_VTK "Uses VTK IO" OFF)
option(MARS_ENABLE_HYPRE "Use -DMARS_ENABLE_HYPRE=ON for enabling Hypre AMG preconditioner" OFF)

# FIXME  and turn on!
option(MARS_ENABLE_SERIAL_BACKEND "Use -DMARS_ENABLE_SERIAL_BACKEND=ON for enabling the serial backend" OFF)
option(MARS_ENABLE_DISTRIBUTED_BACKEND "Use -DMARS_ENABLE_DISTRIBUTED_BACKEND=ON for enabling the distributed backend" ON)
option(MARS_ENABLE_AMR_BACKEND "Use -DMARS_ENABLE_AMR_BACKEND=ON for enabling the AMR backend" OFF)

option(MARS_ENABLE_EXAMPLES "Enable examples" OFF)
option(MARS_ENABLE_FEM_EXAMPLES "Enable FEM examples (unstructured)" OFF)
option(MARS_ENABLE_CXXOPTS "Enable cxxopts" ON)

# MARSIR (MARS FEM operator IR; MIR = MARS Intermediate Representation): build
# the parity example for kernels generated by marsir-compiler/ from an operator
# spec. Generated kernels live under backend/distributed/unstructured/marsir/generated/;
# the compiler itself is a separate build-time tool and is NOT a MARS build
# dependency. OFF by default.
option(MARS_ENABLE_MARSIR "Build the MARSIR generated-kernel parity example (requires UNSTRUCTURED + CUDA)" OFF)

# Unstructured (cornerstone-octree) module. Its kernels are CUDA/HIP only, so it defaults ON
# only in a GPU build; a plain `cmake ..` on a CPU machine then builds the core library.
if(MARS_ENABLE_CUDA OR MARS_ENABLE_HIP)
    option(MARS_ENABLE_UNSTRUCTURED "Enable unstructured module (needs CUDA or HIP)" ON)
else()
    option(MARS_ENABLE_UNSTRUCTURED "Enable unstructured module (needs CUDA or HIP)" OFF)
endif()
if(MARS_ENABLE_UNSTRUCTURED AND NOT (MARS_ENABLE_CUDA OR MARS_ENABLE_HIP))
    message(FATAL_ERROR
        "MARS_ENABLE_UNSTRUCTURED needs a GPU build: add -DMARS_ENABLE_CUDA=ON or "
        "-DMARS_ENABLE_HIP=ON, or set -DMARS_ENABLE_UNSTRUCTURED=OFF for a CPU-only build.")
endif()