include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build_base
  - build # build stage is running on the Kubernetes cluster
  - test # test stage is running on a slurm cluster

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/mars_mc:$CI_COMMIT_SHA
  UTOPIA_CASE_PATH: '/utopia.src/ci/cases/'

build-mars-baseimage:
  extends: .container-builder
  stage: build_base
  before_script:
    - DATA_TAG=`mktemp`
    - sha256sum $DOCKERFILE > $DATA_TAG
    # always use latest branch revision from utopia repo
    - git ls-remote $UTOPIA_GIT_URL $UTOPIA_GIT_REFS >> $DATA_TAG
    - DOCKERFILE_TAG=`sha256sum $DATA_TAG | head -c 16`
    - rm -f $DATA_TAG
    - export PERSIST_IMAGE_NAME=$CSCS_REGISTRY_PATH/baseimage/mars_base:$DOCKERFILE_TAG
    - echo "BASE_IMAGE=$PERSIST_IMAGE_NAME" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  variables:
    DOCKERFILE: ci/gitlab/cscs/mc/docker/Dockerfile.base
    UTOPIA_GIT_URL: 'https://bitbucket.org/zulianp/utopia.git'
    UTOPIA_GIT_REFS: 'refs/heads/development'

build-mars:
  extends: .container-builder
  stage: build
  variables:
    DOCKERFILE: ci/gitlab/cscs/mc/docker/Dockerfile
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=$BASE_IMAGE"]'
    GIT_SUBMODULE_STRATEGY: recursive

run-utopia_fe-test:
  extends: .container-runner-daint-mc
  image: $PERSIST_IMAGE_NAME
  variables:
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: "00:10:00"
    USE_MPI: "NO"
  script:
    # the tests are not installed, so we need to run them from the build directory
    - cd /utopia.src/utopia_fe/build
    # run all tests
    - ./utopia_fe_test --verbose

run-utopia_fe-mars:
  extends: .container-runner-daint-mc
  image: $PERSIST_IMAGE_NAME
  variables:
    SLURM_NTASKS: 1
    SLURM_CPUS_PER_TASK: 18
    SLURM_TIMELIMIT: "00:10:00"
    OMP_NUM_THREADS: 18
    USE_MPI: "NO"
  script:
    # the tests are not installed, so we need to run them from the build directory
    - cd /utopia.src/utopia_fe/build
    # run all tests
    - ./utopia_fe_exec --verbose -backend mars @file $UTOPIA_CASE_PATH/elasticity.yaml